-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.announcements (
  announcement_id text NOT NULL,
  tag_type text NOT NULL CHECK (tag_type = ANY (ARRAY['new'::text, 'alert'::text, 'offer'::text, 'sold_out'::text, 'event'::text])),
  headline text NOT NULL,
  sub_text text,
  cta_label text,
  cta_link text,
  background_image_url text,
  trip_id text,
  display_order integer DEFAULT 1,
  is_active boolean NOT NULL DEFAULT true,
  starts_at timestamp with time zone,
  ends_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT announcements_pkey PRIMARY KEY (announcement_id),
  CONSTRAINT announcements_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(trip_id)
);
CREATE TABLE public.attachments (
  attachment_id text NOT NULL,
  entity_type text NOT NULL CHECK (entity_type = ANY (ARRAY['lead'::text, 'lead_trip'::text, 'customized_trip_request'::text, 'trip'::text, 'booking'::text, 'customer'::text, 'vendor'::text, 'vendor_booking'::text, 'vendor_invoice'::text, 'invoice'::text, 'credit_note'::text, 'cancellation'::text, 'trip_checklist_item'::text, 'task'::text, 'communications_log'::text])),
  entity_id text NOT NULL,
  file_name text NOT NULL,
  file_url text NOT NULL,
  mime_type text,
  file_size_bytes bigint,
  category text CHECK (category IS NULL OR (category = ANY (ARRAY['id_proof'::text, 'ticket'::text, 'voucher'::text, 'invoice'::text, 'contract'::text, 'photo'::text, 'document'::text, 'other'::text]))),
  caption text,
  uploaded_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT attachments_pkey PRIMARY KEY (attachment_id),
  CONSTRAINT attachments_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.team_members(member_id)
);
CREATE TABLE public.audit_log (
  log_id bigint NOT NULL DEFAULT nextval('audit_log_log_id_seq'::regclass),
  table_name text NOT NULL,
  record_id text NOT NULL,
  action text NOT NULL CHECK (action = ANY (ARRAY['INSERT'::text, 'UPDATE'::text, 'DELETE'::text])),
  old_values jsonb,
  new_values jsonb,
  performed_by text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_log_pkey PRIMARY KEY (log_id)
);
CREATE TABLE public.booking_passengers (
  passenger_id text NOT NULL,
  booking_id text NOT NULL,
  customer_id text,
  is_primary boolean NOT NULL DEFAULT false,
  is_lead_passenger boolean NOT NULL DEFAULT false,
  full_name text NOT NULL,
  dob date,
  gender text CHECK (gender = ANY (ARRAY['male'::text, 'female'::text, 'other'::text, 'prefer_not_to_say'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  passport_number text,
  passport_expiry date,
  nationality text,
  dietary_preference text CHECK (dietary_preference = ANY (ARRAY['veg'::text, 'non_veg'::text, 'vegan'::text, 'jain'::text, 'no_preference'::text])),
  special_needs text,
  emergency_contact_name text,
  emergency_contact_phone text,
  emergency_contact_relation text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  role_in_booking text CHECK (role_in_booking = ANY (ARRAY['primary'::text, 'co_traveller'::text, 'child'::text, 'dependent'::text, 'other'::text])),
  CONSTRAINT booking_passengers_pkey PRIMARY KEY (passenger_id),
  CONSTRAINT booking_passengers_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(booking_id),
  CONSTRAINT booking_passengers_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(customer_id)
);
CREATE TABLE public.booking_payments (
  payment_id text NOT NULL,
  booking_id text NOT NULL,
  amount numeric,
  payment_date date,
  payment_method text CHECK (payment_method = ANY (ARRAY['UPI'::text, 'Bank Transfer'::text, 'Cash'::text, 'Card'::text, 'Other'::text, 'Debit Card'::text, 'Credit Card'::text, 'Online'::text])),
  transaction_reference text,
  payment_type text CHECK (payment_type = ANY (ARRAY['Advance'::text, 'Partial'::text, 'Final'::text, 'Refund'::text])),
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  recorded_by text,
  currency_code text DEFAULT 'INR'::text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  pg_transaction_id text,
  payment_order_id text,
  payer_customer_id text,
  money_direction text NOT NULL DEFAULT 'inflow'::text CHECK (money_direction = ANY (ARRAY['inflow'::text, 'outflow'::text])),
  CONSTRAINT booking_payments_pkey PRIMARY KEY (payment_id),
  CONSTRAINT booking_payments_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(booking_id),
  CONSTRAINT booking_payments_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES public.team_members(member_id),
  CONSTRAINT booking_payments_pg_transaction_id_fkey FOREIGN KEY (pg_transaction_id) REFERENCES public.pg_transactions(pg_transaction_id),
  CONSTRAINT booking_payments_payment_order_id_fkey FOREIGN KEY (payment_order_id) REFERENCES public.payment_orders(payment_order_id),
  CONSTRAINT booking_payments_payer_customer_id_fkey FOREIGN KEY (payer_customer_id) REFERENCES public.customers(customer_id)
);
CREATE TABLE public.booking_service_customers (
  booking_service_customer_id text NOT NULL,
  booking_service_id text NOT NULL,
  customer_id text NOT NULL,
  coverage_status text NOT NULL DEFAULT 'included'::text CHECK (coverage_status = ANY (ARRAY['included'::text, 'cancelled'::text, 'fulfilled'::text])),
  share_amount numeric,
  share_tax_amount numeric,
  share_total_amount numeric,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT booking_service_customers_pkey PRIMARY KEY (booking_service_customer_id),
  CONSTRAINT booking_service_customers_booking_service_id_fkey FOREIGN KEY (booking_service_id) REFERENCES public.booking_services(booking_service_id),
  CONSTRAINT booking_service_customers_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(customer_id)
);
CREATE TABLE public.booking_services (
  booking_service_id text NOT NULL,
  booking_id text NOT NULL,
  service_type text NOT NULL CHECK (service_type = ANY (ARRAY['trip_package'::text, 'hotel'::text, 'flight'::text, 'visa'::text, 'transfer'::text, 'activity'::text, 'insurance'::text, 'planning_fee'::text, 'other'::text])),
  commercial_type text NOT NULL CHECK (commercial_type = ANY (ARRAY['package'::text, 'addon_service'::text, 'standalone_service'::text])),
  title text NOT NULL,
  description text,
  service_status text NOT NULL DEFAULT 'draft'::text CHECK (service_status = ANY (ARRAY['draft'::text, 'quoted'::text, 'pending'::text, 'confirmed'::text, 'partially_paid'::text, 'paid'::text, 'fulfilled'::text, 'cancelled'::text])),
  quantity integer,
  unit_price numeric,
  base_amount numeric,
  service_charge_amount numeric,
  taxable_amount numeric,
  gst_rate numeric,
  gst_amount numeric,
  total_amount numeric,
  currency_code text DEFAULT 'INR'::text,
  starts_at timestamp with time zone,
  ends_at timestamp with time zone,
  preferred_vendor_id text,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT booking_services_pkey PRIMARY KEY (booking_service_id),
  CONSTRAINT booking_services_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(booking_id),
  CONSTRAINT booking_services_preferred_vendor_id_fkey FOREIGN KEY (preferred_vendor_id) REFERENCES public.vendors(vendor_id)
);
CREATE TABLE public.bookings (
  booking_id text NOT NULL,
  trip_id text,
  customer_id text NOT NULL,
  lead_trip_id text,
  request_id text,
  sde_id text DEFAULT 'system'::text,
  booking_name text,
  number_of_passengers integer DEFAULT 1,
  booking_date date DEFAULT CURRENT_DATE,
  departure_date date,
  booking_source_type text DEFAULT 'Organic'::text CHECK (booking_source_type = ANY (ARRAY['Organic'::text, 'Paid'::text])),
  booking_source text NOT NULL DEFAULT 'website'::text,
  booking_platform text,
  booking_status text DEFAULT 'Pending'::text CHECK (booking_status = ANY (ARRAY['Pending'::text, 'Confirmed'::text, 'Partial'::text, 'Paid'::text, 'Cancelled'::text, 'Refunded'::text, 'Waitlisted'::text, 'Expired'::text])),
  total_amount numeric,
  advance_amount numeric,
  amount_paid numeric DEFAULT 0,
  balance_due numeric,
  payment_due_date date,
  expires_at timestamp with time zone,
  checkout_variant text CHECK (checkout_variant = ANY (ARRAY['login'::text, 'guest'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  cancellation_policy_id text,
  internal_notes text,
  coupon_code text,
  discount_amount numeric,
  booking_kind text NOT NULL DEFAULT 'trip'::text CHECK (booking_kind = ANY (ARRAY['trip'::text, 'service'::text, 'mixed'::text])),
  booked_by_user_id text,
  service_start_date date,
  service_end_date date,
  currency_code text DEFAULT 'INR'::text,
  rooming_preference text CHECK (rooming_preference IS NULL OR (rooming_preference = ANY (ARRAY['shared'::text, 'separate'::text]))),
  CONSTRAINT bookings_pkey PRIMARY KEY (booking_id),
  CONSTRAINT bookings_cancellation_policy_id_fkey FOREIGN KEY (cancellation_policy_id) REFERENCES public.cancellation_policies(policy_id),
  CONSTRAINT bookings_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(customer_id),
  CONSTRAINT bookings_booked_by_user_id_fkey FOREIGN KEY (booked_by_user_id) REFERENCES public.users(user_id),
  CONSTRAINT bookings_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(trip_id),
  CONSTRAINT bookings_lead_trip_id_fkey FOREIGN KEY (lead_trip_id) REFERENCES public.lead_trips(lead_trip_id),
  CONSTRAINT bookings_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.customized_trip_requests(request_id),
  CONSTRAINT bookings_sde_id_fkey FOREIGN KEY (sde_id) REFERENCES public.team_members(member_id)
);
CREATE TABLE public.cancellation_policies (
  policy_id text NOT NULL,
  policy_key text NOT NULL UNIQUE,
  policy_name text NOT NULL,
  description text,
  applies_to_origin text CHECK (applies_to_origin IS NULL OR (applies_to_origin = ANY (ARRAY['Group Trip'::text, 'Customized Trip'::text, 'any'::text]))),
  applies_to_scope text CHECK (applies_to_scope IS NULL OR (applies_to_scope = ANY (ARRAY['domestic'::text, 'international'::text, 'any'::text]))),
  advance_non_refundable boolean NOT NULL DEFAULT false,
  batch_change_same_as_cancel boolean NOT NULL DEFAULT true,
  force_majeure_refund boolean NOT NULL DEFAULT false,
  replacement_allowed boolean NOT NULL DEFAULT false,
  replacement_cutoff_days integer,
  refund_sla_days integer,
  raw_text text,
  is_active boolean NOT NULL DEFAULT true,
  created_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT cancellation_policies_pkey PRIMARY KEY (policy_id),
  CONSTRAINT cancellation_policies_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.team_members(member_id)
);
CREATE TABLE public.cancellation_policy_slabs (
  slab_id text NOT NULL,
  policy_id text NOT NULL,
  slab_order integer NOT NULL DEFAULT 0,
  min_days_before integer,
  max_days_before integer,
  fee_type text NOT NULL CHECK (fee_type = ANY (ARRAY['percentage'::text, 'advance_forfeit'::text, 'fixed_amount'::text])),
  fee_value numeric NOT NULL DEFAULT 0,
  refund_remaining boolean NOT NULL DEFAULT true,
  label text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT cancellation_policy_slabs_pkey PRIMARY KEY (slab_id),
  CONSTRAINT cancellation_policy_slabs_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.cancellation_policies(policy_id)
);
CREATE TABLE public.cancellations (
  cancellation_id text NOT NULL,
  booking_id text NOT NULL,
  initiated_by text,
  initiated_at timestamp with time zone NOT NULL DEFAULT now(),
  reason_category text NOT NULL CHECK (reason_category = ANY (ARRAY['customer_request'::text, 'medical'::text, 'vendor_failure'::text, 'ops_decision'::text, 'weather'::text, 'force_majeure'::text, 'no_show'::text, 'other'::text, 'Operator Cancellation'::text, 'Duplicate Booking'::text])),
  reason_text text,
  days_before_departure integer,
  gross_amount numeric NOT NULL,
  cancellation_fee_pct numeric,
  cancellation_fee_amount numeric NOT NULL DEFAULT 0,
  refund_amount numeric NOT NULL DEFAULT 0,
  credit_note_id text,
  pg_refund_id text,
  status text NOT NULL DEFAULT 'Pending'::text CHECK (status = ANY (ARRAY['Pending'::text, 'Approved'::text, 'Processed'::text, 'Rejected'::text, 'Refund Processing'::text, 'Completed'::text])),
  approved_by text,
  approved_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  offline_refund_date date,
  offline_refund_reference text,
  booking_service_id text,
  CONSTRAINT cancellations_pkey PRIMARY KEY (cancellation_id),
  CONSTRAINT cancellations_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(booking_id),
  CONSTRAINT cancellations_initiated_by_fkey FOREIGN KEY (initiated_by) REFERENCES public.team_members(member_id),
  CONSTRAINT cancellations_credit_note_id_fkey FOREIGN KEY (credit_note_id) REFERENCES public.credit_notes(credit_note_id),
  CONSTRAINT cancellations_pg_refund_id_fkey FOREIGN KEY (pg_refund_id) REFERENCES public.pg_refunds(pg_refund_id),
  CONSTRAINT cancellations_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.team_members(member_id),
  CONSTRAINT cancellations_booking_service_id_fkey FOREIGN KEY (booking_service_id) REFERENCES public.booking_services(booking_service_id)
);
CREATE TABLE public.career_listings (
  career_id text NOT NULL,
  title text NOT NULL,
  department text NOT NULL,
  location text DEFAULT 'Remote'::text,
  employment_type text DEFAULT 'full-time'::text CHECK (employment_type = ANY (ARRAY['full-time'::text, 'part-time'::text, 'contract'::text, 'internship'::text])),
  description text,
  responsibilities ARRAY DEFAULT '{}'::text[],
  requirements ARRAY DEFAULT '{}'::text[],
  is_open boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT career_listings_pkey PRIMARY KEY (career_id)
);
CREATE TABLE public.checklist_template_items (
  template_item_id text NOT NULL,
  template_id text NOT NULL,
  item_order integer NOT NULL DEFAULT 0,
  category text,
  title text NOT NULL,
  description text,
  default_assignee_role text CHECK (default_assignee_role IS NULL OR (default_assignee_role = ANY (ARRAY['Admin'::text, 'Sales'::text, 'Operations'::text, 'Finance'::text, 'Marketing'::text]))),
  offset_days integer NOT NULL DEFAULT 0,
  is_mandatory boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  stage text CHECK (stage = ANY (ARRAY['Pre-Trip'::text, 'Group Trip Prep'::text, 'WhatsApp Group'::text, 'On-Trip'::text, 'Post-Trip'::text])),
  CONSTRAINT checklist_template_items_pkey PRIMARY KEY (template_item_id),
  CONSTRAINT checklist_template_items_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.checklist_templates(template_id)
);
CREATE TABLE public.checklist_templates (
  template_id text NOT NULL,
  template_name text NOT NULL,
  description text,
  applies_to text NOT NULL DEFAULT 'all'::text CHECK (applies_to = ANY (ARRAY['all'::text, 'domestic'::text, 'international'::text, 'custom'::text])),
  is_active boolean NOT NULL DEFAULT true,
  created_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT checklist_templates_pkey PRIMARY KEY (template_id),
  CONSTRAINT checklist_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.team_members(member_id)
);
CREATE TABLE public.communications_log (
  comm_id text NOT NULL,
  channel text NOT NULL CHECK (channel = ANY (ARRAY['whatsapp'::text, 'email'::text, 'sms'::text, 'call'::text, 'in_person'::text, 'other'::text, 'facebook_dm'::text, 'instagram_dm'::text, 'facebook_comment'::text, 'instagram_comment'::text])),
  direction text NOT NULL CHECK (direction = ANY (ARRAY['inbound'::text, 'outbound'::text])),
  template_id text,
  notification_id text,
  entity_type text CHECK (entity_type IS NULL OR (entity_type = ANY (ARRAY['lead'::text, 'lead_trip'::text, 'customized_trip_request'::text, 'trip'::text, 'booking'::text, 'customer'::text, 'vendor'::text]))),
  entity_id text,
  customer_id text,
  lead_id text,
  booking_id text,
  vendor_id text,
  to_address text,
  from_address text,
  subject text,
  body text,
  status text NOT NULL DEFAULT 'sent'::text CHECK (status = ANY (ARRAY['sent'::text, 'delivered'::text, 'read'::text, 'failed'::text, 'bounced'::text, 'queued'::text])),
  provider text,
  provider_message_id text,
  error_message text,
  metadata jsonb,
  sent_by text,
  occurred_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT communications_log_pkey PRIMARY KEY (comm_id),
  CONSTRAINT communications_log_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(customer_id),
  CONSTRAINT communications_log_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(lead_id),
  CONSTRAINT communications_log_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.message_templates(template_id),
  CONSTRAINT communications_log_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(booking_id),
  CONSTRAINT communications_log_sent_by_fkey FOREIGN KEY (sent_by) REFERENCES public.team_members(member_id),
  CONSTRAINT communications_log_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(vendor_id)
);
CREATE TABLE public.costing_items (
  item_id text NOT NULL,
  costing_id text NOT NULL,
  category text NOT NULL,
  description text NOT NULL,
  num_pax integer,
  cost_basis text NOT NULL CHECK (cost_basis = ANY (ARRAY['flat_total'::text, 'per_person'::text, 'per_person_per_night'::text, 'per_room_per_night'::text, 'per_vehicle_per_day'::text, 'per_unit'::text])),
  quantity integer,
  rates jsonb,
  totals jsonb,
  is_shared boolean NOT NULL DEFAULT false,
  vendor_id text,
  notes text,
  display_order integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT costing_items_pkey PRIMARY KEY (item_id),
  CONSTRAINT costing_items_costing_id_fkey FOREIGN KEY (costing_id) REFERENCES public.trip_costings(costing_id),
  CONSTRAINT costing_items_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(vendor_id)
);
CREATE TABLE public.credit_notes (
  credit_note_id text NOT NULL,
  credit_note_number text UNIQUE,
  fy text,
  booking_id text NOT NULL,
  invoice_id text,
  issued_date date NOT NULL DEFAULT CURRENT_DATE,
  reason text NOT NULL,
  subtotal numeric NOT NULL,
  cgst_amount numeric NOT NULL DEFAULT 0,
  sgst_amount numeric NOT NULL DEFAULT 0,
  tcs_amount numeric,
  total_amount numeric NOT NULL,
  currency_code text NOT NULL DEFAULT 'INR'::text,
  status text NOT NULL DEFAULT 'Draft'::text CHECK (status = ANY (ARRAY['Draft'::text, 'Issued'::text, 'Applied'::text, 'Cancelled'::text])),
  linked_refund_id text,
  notes text,
  created_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  booking_service_id text,
  CONSTRAINT credit_notes_pkey PRIMARY KEY (credit_note_id),
  CONSTRAINT credit_notes_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(booking_id),
  CONSTRAINT credit_notes_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(invoice_id),
  CONSTRAINT credit_notes_currency_code_fkey FOREIGN KEY (currency_code) REFERENCES public.currencies(currency_code),
  CONSTRAINT credit_notes_linked_refund_id_fkey FOREIGN KEY (linked_refund_id) REFERENCES public.pg_refunds(pg_refund_id),
  CONSTRAINT credit_notes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.team_members(member_id),
  CONSTRAINT credit_notes_booking_service_id_fkey FOREIGN KEY (booking_service_id) REFERENCES public.booking_services(booking_service_id)
);
CREATE TABLE public.currencies (
  currency_code text NOT NULL,
  symbol text NOT NULL,
  name text NOT NULL,
  decimals integer NOT NULL DEFAULT 2,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT currencies_pkey PRIMARY KEY (currency_code)
);
CREATE TABLE public.customers (
  customer_id text NOT NULL,
  phone text UNIQUE,
  full_name text,
  email text,
  emergency_contact_name text,
  emergency_contact_phone text,
  dob date,
  city text,
  id_proof_type text,
  id_proof_number text,
  id_proof_document_url text,
  dietary_preference text,
  special_needs text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  lead_id text,
  user_id text,
  phone_normalized text,
  created_via text NOT NULL DEFAULT 'self_booking'::text CHECK (created_via = ANY (ARRAY['self_booking'::text, 'co_passenger'::text, 'ops_imported'::text, 'lead_conversion'::text])),
  added_by_user_id text,
  CONSTRAINT customers_pkey PRIMARY KEY (customer_id),
  CONSTRAINT customers_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(lead_id),
  CONSTRAINT fk_customers_user_id FOREIGN KEY (user_id) REFERENCES public.users(user_id),
  CONSTRAINT customers_added_by_user_id_fkey FOREIGN KEY (added_by_user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.customized_trip_requests (
  request_id text NOT NULL,
  lead_id text NOT NULL,
  trip_category text NOT NULL CHECK (trip_category = ANY (ARRAY['Signature Journey'::text, 'Plan a Trip'::text])),
  signature_journey_id text,
  destination_interested text NOT NULL,
  travel_month text,
  travel_dates_from date,
  travel_dates_to date,
  duration text,
  number_of_pax integer NOT NULL,
  who_planning_for text,
  budget_per_person text,
  type_of_experience text,
  occasion text,
  flight_assistance boolean,
  vehicle_type text,
  complete_details text,
  special_requirements text,
  owner_id text,
  pipeline_status text NOT NULL DEFAULT 'New Request'::text CHECK (pipeline_status = ANY (ARRAY['New Request'::text, 'In Discussion'::text, 'Proposal Sent'::text, 'Negotiating'::text, 'Confirmed'::text, 'Lost'::text, 'Moved to Group Trip'::text])),
  source_type text NOT NULL DEFAULT 'Organic'::text CHECK (source_type = ANY (ARRAY['Organic'::text, 'Paid'::text])),
  source text NOT NULL,
  platform text,
  ad_form_responses jsonb,
  quoted_price numeric,
  converted_from_lead_trip_id text,
  converted_to_trip_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  flights_booked boolean,
  visa_assistance boolean,
  total_budget numeric,
  num_adults integer,
  num_kids integer,
  num_senior_citizens integer,
  hotel_category text CHECK (hotel_category = ANY (ARRAY['3_star'::text, '4_star'::text, '5_star'::text])),
  trip_style text CHECK (trip_style = ANY (ARRAY['budget'::text, 'premium'::text, 'luxury'::text])),
  specific_experiences text,
  CONSTRAINT customized_trip_requests_pkey PRIMARY KEY (request_id),
  CONSTRAINT customized_trip_requests_signature_journey_id_fkey FOREIGN KEY (signature_journey_id) REFERENCES public.signature_journeys(signature_journey_id),
  CONSTRAINT customized_trip_requests_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.team_members(member_id),
  CONSTRAINT customized_trip_requests_converted_to_trip_id_fkey FOREIGN KEY (converted_to_trip_id) REFERENCES public.trips(trip_id),
  CONSTRAINT customized_trip_requests_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(lead_id),
  CONSTRAINT customized_trip_requests_converted_from_lead_trip_id_fkey FOREIGN KEY (converted_from_lead_trip_id) REFERENCES public.lead_trips(lead_trip_id)
);
CREATE TABLE public.departure_cities (
  departure_city_id text NOT NULL,
  city_name text NOT NULL,
  country_code text NOT NULL,
  country_name text NOT NULL,
  is_popular boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  display_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT departure_cities_pkey PRIMARY KEY (departure_city_id)
);
CREATE TABLE public.destinations (
  destination_id text NOT NULL,
  destination_code text NOT NULL UNIQUE,
  destination_name text NOT NULL,
  country text NOT NULL,
  is_domestic boolean NOT NULL DEFAULT true,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  icon text,
  description text,
  display_order integer DEFAULT 0,
  CONSTRAINT destinations_pkey PRIMARY KEY (destination_id)
);
CREATE TABLE public.enum_values (
  id text NOT NULL,
  category text NOT NULL,
  value text NOT NULL,
  label text NOT NULL,
  display_order integer,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT enum_values_pkey PRIMARY KEY (id)
);
CREATE TABLE public.exchange_rates (
  rate_id text NOT NULL,
  from_currency text NOT NULL,
  to_currency text NOT NULL,
  rate numeric NOT NULL CHECK (rate > 0::numeric),
  source text NOT NULL DEFAULT 'manual'::text,
  effective_date date NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT exchange_rates_pkey PRIMARY KEY (rate_id),
  CONSTRAINT exchange_rates_from_currency_fkey FOREIGN KEY (from_currency) REFERENCES public.currencies(currency_code),
  CONSTRAINT exchange_rates_to_currency_fkey FOREIGN KEY (to_currency) REFERENCES public.currencies(currency_code)
);
CREATE TABLE public.exclusions (
  exclusion_id text NOT NULL,
  name text NOT NULL UNIQUE,
  category text NOT NULL DEFAULT 'Other'::text,
  is_popular boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  display_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT exclusions_pkey PRIMARY KEY (exclusion_id)
);
CREATE TABLE public.id_counters (
  scope text NOT NULL,
  next_value bigint NOT NULL DEFAULT 1,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT id_counters_pkey PRIMARY KEY (scope)
);
CREATE TABLE public.identity_cards (
  identity_card_id text NOT NULL,
  icon text NOT NULL,
  card_type text NOT NULL,
  description text NOT NULL,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT identity_cards_pkey PRIMARY KEY (identity_card_id)
);
CREATE TABLE public.inclusion_chips (
  chip_id text NOT NULL,
  name text NOT NULL UNIQUE,
  icon text NOT NULL,
  category text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  display_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT inclusion_chips_pkey PRIMARY KEY (chip_id)
);
CREATE TABLE public.invoice_sequences (
  fy text NOT NULL,
  invoice_type text NOT NULL CHECK (invoice_type = ANY (ARRAY['Invoice'::text, 'Proforma Invoice'::text, 'Credit Note'::text])),
  prefix text NOT NULL,
  next_number integer NOT NULL DEFAULT 1,
  padding integer NOT NULL DEFAULT 4,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT invoice_sequences_pkey PRIMARY KEY (fy, invoice_type)
);
CREATE TABLE public.invoices (
  invoice_id text NOT NULL,
  invoice_type text NOT NULL CHECK (invoice_type = ANY (ARRAY['Invoice'::text, 'Proforma Invoice'::text, 'Receipt Voucher'::text])),
  booking_id text NOT NULL,
  invoice_date date NOT NULL,
  due_date date,
  subtotal numeric NOT NULL,
  tcs_amount numeric,
  total_amount numeric NOT NULL,
  status text NOT NULL DEFAULT 'Draft'::text CHECK (status = ANY (ARRAY['Draft'::text, 'Issued'::text, 'Paid'::text, 'Cancelled'::text, 'Void'::text])),
  gstin text NOT NULL,
  hsn_sac text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  invoice_number text,
  fy text,
  currency_code text DEFAULT 'INR'::text,
  gst_amount numeric NOT NULL DEFAULT 0,
  billed_to_name text,
  billed_to_email text,
  billed_to_phone text,
  billed_to_address text,
  invoice_scope text DEFAULT 'booking'::text CHECK (invoice_scope = ANY (ARRAY['booking'::text, 'service_bundle'::text])),
  CONSTRAINT invoices_pkey PRIMARY KEY (invoice_id),
  CONSTRAINT invoices_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(booking_id),
  CONSTRAINT invoices_currency_code_fkey FOREIGN KEY (currency_code) REFERENCES public.currencies(currency_code)
);
CREATE TABLE public.itinerary_drafts (
  draft_id text NOT NULL,
  request_id text NOT NULL,
  version integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'sent'::text, 'accepted'::text, 'rejected'::text, 'superseded'::text])),
  draft_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  palette text CHECK (palette IS NULL OR (palette = ANY (ARRAY['blue'::text, 'green'::text, 'rust'::text]))),
  title text,
  pdf_url text,
  pdf_generated_at timestamp with time zone,
  sent_at timestamp with time zone,
  sent_to text,
  accepted_at timestamp with time zone,
  rejected_at timestamp with time zone,
  rejection_reason text,
  created_by text,
  updated_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  template_id text,
  is_from_scratch boolean,
  review_status text DEFAULT 'not_required'::text CHECK (review_status = ANY (ARRAY['not_required'::text, 'pending_peer'::text, 'peer_approved'::text, 'pending_manager'::text, 'approved'::text, 'revision_requested'::text])),
  peer_reviewer_id text,
  peer_reviewed_at timestamp with time zone,
  peer_review_notes text,
  manager_reviewer_id text,
  manager_reviewed_at timestamp with time zone,
  manager_review_notes text,
  CONSTRAINT itinerary_drafts_pkey PRIMARY KEY (draft_id),
  CONSTRAINT itinerary_drafts_manager_reviewer_id_fkey FOREIGN KEY (manager_reviewer_id) REFERENCES public.team_members(member_id),
  CONSTRAINT itinerary_drafts_peer_reviewer_id_fkey FOREIGN KEY (peer_reviewer_id) REFERENCES public.team_members(member_id),
  CONSTRAINT itinerary_drafts_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.customized_trip_requests(request_id),
  CONSTRAINT itinerary_drafts_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.team_members(member_id),
  CONSTRAINT itinerary_drafts_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.team_members(member_id),
  CONSTRAINT itinerary_drafts_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.itinerary_templates(template_id)
);
CREATE TABLE public.itinerary_templates (
  template_id text NOT NULL,
  destination_id text,
  title text NOT NULL,
  duration_nights integer,
  duration_days integer,
  trip_category text,
  trip_style text CHECK (trip_style = ANY (ARRAY['budget'::text, 'premium'::text, 'luxury'::text])),
  template_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  usage_count integer DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_by text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT itinerary_templates_pkey PRIMARY KEY (template_id),
  CONSTRAINT itinerary_templates_destination_id_fkey FOREIGN KEY (destination_id) REFERENCES public.destinations(destination_id),
  CONSTRAINT itinerary_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.team_members(member_id)
);
CREATE TABLE public.lead_activities (
  activity_id text NOT NULL,
  lead_id text NOT NULL,
  lead_trip_id text,
  activity_type text NOT NULL CHECK (activity_type = ANY (ARRAY['note'::text, 'call'::text, 'whatsapp'::text, 'email'::text, 'sms'::text, 'status_change'::text, 'quote_sent'::text, 'meeting'::text, 'task_created'::text, 'assignment_change'::text])),
  subject text,
  body text,
  outcome text CHECK (outcome IS NULL OR (outcome = ANY (ARRAY['connected'::text, 'no_answer'::text, 'busy'::text, 'wrong_number'::text, 'not_interested'::text, 'interested'::text, 'followup'::text]))),
  direction text CHECK (direction IS NULL OR (direction = ANY (ARRAY['inbound'::text, 'outbound'::text]))),
  metadata jsonb,
  performed_by text NOT NULL,
  occurred_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  request_id text,
  activity_category text,
  call_status text,
  follow_up_date date,
  follow_up_notes text,
  is_follow_up_completed boolean DEFAULT false,
  scheduled_at timestamp with time zone,
  CONSTRAINT lead_activities_pkey PRIMARY KEY (activity_id),
  CONSTRAINT lead_activities_lead_trip_id_fkey FOREIGN KEY (lead_trip_id) REFERENCES public.lead_trips(lead_trip_id),
  CONSTRAINT lead_activities_performed_by_fkey FOREIGN KEY (performed_by) REFERENCES public.team_members(member_id),
  CONSTRAINT lead_activities_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(lead_id),
  CONSTRAINT lead_activities_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.customized_trip_requests(request_id)
);
CREATE TABLE public.lead_trips (
  lead_trip_id text NOT NULL,
  lead_id text NOT NULL,
  trip_id text,
  trip_slug text,
  source_page text,
  source_cta text,
  context jsonb,
  lead_trip_status text NOT NULL DEFAULT 'new'::text CHECK (lead_trip_status = ANY (ARRAY['new'::text, 'contacted'::text, 'qualified'::text, 'converted'::text, 'lost'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  converted_booking_id text,
  owner_id text,
  converted_to_request_id text,
  CONSTRAINT lead_trips_pkey PRIMARY KEY (lead_trip_id),
  CONSTRAINT lead_trips_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(trip_id),
  CONSTRAINT lead_trips_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(lead_id),
  CONSTRAINT lead_trips_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.team_members(member_id),
  CONSTRAINT lead_trips_converted_to_request_id_fkey FOREIGN KEY (converted_to_request_id) REFERENCES public.customized_trip_requests(request_id),
  CONSTRAINT lead_trips_converted_booking_id_fkey FOREIGN KEY (converted_booking_id) REFERENCES public.bookings(booking_id)
);
CREATE TABLE public.leads (
  lead_id text NOT NULL,
  phone text NOT NULL UNIQUE,
  full_name text,
  email text,
  first_source text,
  first_seen_at timestamp with time zone NOT NULL DEFAULT now(),
  last_activity_at timestamp with time zone NOT NULL DEFAULT now(),
  lead_status text NOT NULL DEFAULT 'New'::text CHECK (lead_status = ANY (ARRAY['New'::text, 'Call Scheduled'::text, 'Itinerary Shared'::text, 'Follow Up'::text, 'Converted'::text, 'Closed'::text, 'Cancelled'::text, 'Refunded'::text])),
  sde_id text NOT NULL DEFAULT 'system'::text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  phone_country_code text,
  phone_normalized text,
  alt_phone text,
  alt_phone_country_code text,
  alt_phone_normalized text,
  city text,
  dob date,
  lead_type text,
  platform text,
  destination_interested text,
  destination_id text,
  trip_type text,
  trip_sub_type text,
  trip_category text,
  is_actionable boolean,
  reason_for_closure text,
  package_status text CHECK ((package_status = ANY (ARRAY['Not Started'::text, 'Sent'::text, 'Not Needed'::text])) OR package_status IS NULL),
  travel_month text,
  hotel_category text CHECK ((hotel_category = ANY (ARRAY['Budget'::text, 'Standard'::text, 'Deluxe'::text, 'Luxury'::text])) OR hotel_category IS NULL),
  trip_style text CHECK ((trip_style = ANY (ARRAY['Budget'::text, 'Premium'::text, 'Luxury'::text])) OR trip_style IS NULL),
  revenue_opportunity numeric,
  num_pax integer,
  budget_per_person numeric,
  user_id text,
  customer_id text,
  meta_leadgen_id text,
  meta_form_id text,
  meta_form_name text,
  meta_page_id text,
  meta_ad_id text,
  meta_adgroup_id text,
  meta_campaign_id text,
  meta_created_time timestamp with time zone,
  meta_platform text,
  meta_is_organic boolean,
  meta_field_data jsonb DEFAULT '[]'::jsonb,
  meta_raw_payload jsonb DEFAULT '{}'::jsonb,
  sync_source text DEFAULT 'manual'::text,
  sync_status text DEFAULT 'pending'::text CHECK (sync_status = ANY (ARRAY['pending'::text, 'retrying'::text, 'synced'::text, 'failed'::text])),
  sync_attempts integer DEFAULT 0,
  sync_last_attempt_at timestamp with time zone,
  sync_next_retry_at timestamp with time zone,
  sync_last_error text,
  sync_external_id text,
  meta_mapping_status text DEFAULT 'ready'::text CHECK (meta_mapping_status = ANY (ARRAY['ready'::text, 'needs_review'::text, 'blocked'::text])),
  meta_missing_required_fields jsonb DEFAULT '[]'::jsonb,
  meta_blocked_reason text,
  CONSTRAINT leads_pkey PRIMARY KEY (lead_id),
  CONSTRAINT leads_sde_id_fkey FOREIGN KEY (sde_id) REFERENCES public.team_members(member_id),
  CONSTRAINT leads_destination_id_fkey FOREIGN KEY (destination_id) REFERENCES public.destinations(destination_id)
);
CREATE TABLE public.message_templates (
  template_id text NOT NULL,
  template_key text NOT NULL UNIQUE,
  template_name text NOT NULL,
  channel text NOT NULL CHECK (channel = ANY (ARRAY['whatsapp'::text, 'email'::text, 'sms'::text])),
  category text NOT NULL CHECK (category = ANY (ARRAY['quote'::text, 'booking'::text, 'payment'::text, 'pre_departure'::text, 'on_trip'::text, 'post_trip'::text, 'marketing'::text, 'cancellation'::text, 'generic'::text])),
  subject text,
  body text NOT NULL,
  variables jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT message_templates_pkey PRIMARY KEY (template_id),
  CONSTRAINT message_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.team_members(member_id)
);
CREATE TABLE public.meta_form_question_map (
  id bigint NOT NULL DEFAULT nextval('meta_form_question_map_id_seq'::regclass),
  form_id text,
  meta_question_key text NOT NULL,
  target_field text NOT NULL,
  transform_type text NOT NULL DEFAULT 'text'::text CHECK (transform_type = ANY (ARRAY['text'::text, 'number'::text, 'integer'::text, 'trip_type'::text, 'trip_category'::text, 'city'::text])),
  default_value text,
  is_required boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_by text,
  updated_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT meta_form_question_map_pkey PRIMARY KEY (id),
  CONSTRAINT meta_form_question_map_form_id_fkey FOREIGN KEY (form_id) REFERENCES public.meta_form_registry(form_id)
);
CREATE TABLE public.meta_form_registry (
  form_id text NOT NULL,
  page_id text,
  form_name text,
  status text,
  locale text,
  is_active boolean NOT NULL DEFAULT true,
  approval_status text NOT NULL DEFAULT 'pending'::text CHECK (approval_status = ANY (ARRAY['pending'::text, 'approved'::text, 'blocked'::text])),
  required_fields_ok boolean NOT NULL DEFAULT false,
  approved_by text,
  approved_at timestamp with time zone,
  last_seen_at timestamp with time zone,
  last_polled_at timestamp with time zone,
  last_error text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT meta_form_registry_pkey PRIMARY KEY (form_id)
);
CREATE TABLE public.meta_lead_events (
  id bigint NOT NULL DEFAULT nextval('meta_lead_events_id_seq'::regclass),
  event_source text NOT NULL CHECK (event_source = ANY (ARRAY['webhook'::text, 'poll'::text])),
  page_id text,
  form_id text,
  leadgen_id text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_processed boolean NOT NULL DEFAULT false,
  process_error text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  processed_at timestamp with time zone,
  CONSTRAINT meta_lead_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.meta_oauth_connections (
  id bigint NOT NULL DEFAULT nextval('meta_oauth_connections_id_seq'::regclass),
  provider text NOT NULL DEFAULT 'meta'::text,
  token_kind text NOT NULL DEFAULT 'page'::text CHECK (token_kind = ANY (ARRAY['page'::text, 'user'::text])),
  page_id text,
  page_name text,
  access_token_enc text NOT NULL,
  scopes ARRAY NOT NULL DEFAULT '{}'::text[],
  expires_at timestamp with time zone,
  is_valid boolean NOT NULL DEFAULT true,
  is_active boolean NOT NULL DEFAULT false,
  last_validated_at timestamp with time zone,
  last_validation_error text,
  created_by text,
  updated_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT meta_oauth_connections_pkey PRIMARY KEY (id)
);
CREATE TABLE public.meta_social_messages (
  id bigint NOT NULL DEFAULT nextval('meta_social_messages_id_seq'::regclass),
  message_id text NOT NULL UNIQUE,
  thread_id text NOT NULL,
  page_id text,
  platform text NOT NULL DEFAULT 'facebook'::text CHECK (platform = ANY (ARRAY['facebook'::text, 'instagram'::text])),
  message_type text NOT NULL DEFAULT 'dm'::text CHECK (message_type = ANY (ARRAY['dm'::text, 'comment'::text])),
  direction text NOT NULL DEFAULT 'inbound'::text CHECK (direction = ANY (ARRAY['inbound'::text, 'outbound'::text, 'system'::text])),
  sender_id text,
  sender_name text,
  message_text text,
  created_time timestamp with time zone,
  extracted_email text,
  extracted_phone text,
  destination_hint text,
  lead_id text,
  synced_to_lead boolean NOT NULL DEFAULT false,
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT meta_social_messages_pkey PRIMARY KEY (id),
  CONSTRAINT meta_social_messages_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES public.meta_social_threads(thread_id),
  CONSTRAINT meta_social_messages_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(lead_id)
);
CREATE TABLE public.meta_social_sync_state (
  id text NOT NULL,
  page_id text NOT NULL,
  sync_kind text NOT NULL CHECK (sync_kind = ANY (ARRAY['dm'::text, 'comment'::text])),
  next_after_cursor text,
  last_polled_at timestamp with time zone,
  last_success_at timestamp with time zone,
  last_error text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT meta_social_sync_state_pkey PRIMARY KEY (id)
);
CREATE TABLE public.meta_social_threads (
  id bigint NOT NULL DEFAULT nextval('meta_social_threads_id_seq'::regclass),
  thread_id text NOT NULL UNIQUE,
  page_id text,
  platform text NOT NULL DEFAULT 'facebook'::text CHECK (platform = ANY (ARRAY['facebook'::text, 'instagram'::text])),
  source_type text NOT NULL DEFAULT 'dm'::text CHECK (source_type = ANY (ARRAY['dm'::text, 'comment'::text])),
  participant_id text,
  participant_name text,
  prospect_status text NOT NULL DEFAULT 'new'::text CHECK (prospect_status = ANY (ARRAY['new'::text, 'qualified'::text, 'ignored'::text, 'spam'::text])),
  lead_id text,
  destination_hint text,
  trip_type_hint text,
  latest_message_preview text,
  latest_message_at timestamp with time zone,
  unread_count integer NOT NULL DEFAULT 0,
  is_action_required boolean NOT NULL DEFAULT true,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT meta_social_threads_pkey PRIMARY KEY (id),
  CONSTRAINT meta_social_threads_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(lead_id)
);
CREATE TABLE public.meta_sync_state (
  form_id text NOT NULL,
  page_id text,
  next_after_cursor text,
  last_polled_at timestamp with time zone,
  last_success_at timestamp with time zone,
  last_error text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT meta_sync_state_pkey PRIMARY KEY (form_id)
);
CREATE TABLE public.nomichi_ops_settings (
  id text NOT NULL DEFAULT 'main'::text,
  data jsonb NOT NULL,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT nomichi_ops_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.nomichi_ops_trips (
  id text NOT NULL DEFAULT 'main'::text,
  data jsonb NOT NULL,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT nomichi_ops_trips_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notification_queue (
  notification_id text NOT NULL DEFAULT (gen_random_uuid())::text,
  template_key text NOT NULL,
  channels ARRAY NOT NULL,
  recipient jsonb NOT NULL,
  variables jsonb,
  idempotency_key text UNIQUE,
  status text NOT NULL DEFAULT 'queued'::text CHECK (status = ANY (ARRAY['queued'::text, 'sending'::text, 'sent'::text, 'failed'::text, 'skipped'::text])),
  attempts integer NOT NULL DEFAULT 0,
  last_error text,
  scheduled_for timestamp with time zone NOT NULL DEFAULT now(),
  sent_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notification_queue_pkey PRIMARY KEY (notification_id)
);
CREATE TABLE public.ops_alerts (
  alert_id text NOT NULL DEFAULT (gen_random_uuid())::text,
  severity text NOT NULL DEFAULT 'info'::text CHECK (severity = ANY (ARRAY['info'::text, 'warning'::text, 'critical'::text])),
  category text NOT NULL,
  subject text NOT NULL,
  context jsonb,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ops_alerts_pkey PRIMARY KEY (alert_id)
);
CREATE TABLE public.otp_codes (
  otp_id text NOT NULL,
  phone text NOT NULL,
  code_hash text NOT NULL,
  channel_attempted text CHECK (channel_attempted = ANY (ARRAY['whatsapp'::text, 'sms'::text])),
  channel_delivered text CHECK (channel_delivered = ANY (ARRAY['whatsapp'::text, 'sms'::text])),
  expires_at timestamp with time zone NOT NULL,
  attempts integer NOT NULL DEFAULT 0,
  consumed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  intent text CHECK (intent IS NULL OR (intent = ANY (ARRAY['join'::text, 'booking'::text, 'callback'::text]))),
  CONSTRAINT otp_codes_pkey PRIMARY KEY (otp_id)
);
CREATE TABLE public.page_hero_images (
  page_key text NOT NULL,
  image_light text,
  image_dark text,
  alt_text text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT page_hero_images_pkey PRIMARY KEY (page_key)
);
CREATE TABLE public.payment_allocations (
  payment_allocation_id text NOT NULL,
  payment_id text NOT NULL,
  booking_service_id text,
  booking_service_customer_id text,
  allocation_type text NOT NULL CHECK (allocation_type = ANY (ARRAY['principal'::text, 'refund'::text, 'adjustment'::text, 'credit_use'::text])),
  amount numeric NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_allocations_pkey PRIMARY KEY (payment_allocation_id),
  CONSTRAINT payment_allocations_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.booking_payments(payment_id),
  CONSTRAINT payment_allocations_booking_service_id_fkey FOREIGN KEY (booking_service_id) REFERENCES public.booking_services(booking_service_id),
  CONSTRAINT payment_allocations_booking_service_customer_id_fkey FOREIGN KEY (booking_service_customer_id) REFERENCES public.booking_service_customers(booking_service_customer_id)
);
CREATE TABLE public.payment_order_targets (
  payment_order_target_id text NOT NULL,
  payment_order_id text NOT NULL,
  booking_service_id text,
  booking_service_customer_id text,
  intended_amount numeric NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_order_targets_pkey PRIMARY KEY (payment_order_target_id),
  CONSTRAINT payment_order_targets_payment_order_id_fkey FOREIGN KEY (payment_order_id) REFERENCES public.payment_orders(payment_order_id),
  CONSTRAINT payment_order_targets_booking_service_id_fkey FOREIGN KEY (booking_service_id) REFERENCES public.booking_services(booking_service_id),
  CONSTRAINT payment_order_targets_booking_service_customer_id_fkey FOREIGN KEY (booking_service_customer_id) REFERENCES public.booking_service_customers(booking_service_customer_id)
);
CREATE TABLE public.payment_orders (
  payment_order_id text NOT NULL,
  booking_id text NOT NULL,
  customer_id text NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  currency text NOT NULL DEFAULT 'INR'::text,
  payment_type text NOT NULL CHECK (payment_type = ANY (ARRAY['Advance'::text, 'Partial'::text, 'Final'::text])),
  provider text NOT NULL,
  provider_order_id text,
  payment_session_id text,
  status text NOT NULL DEFAULT 'CREATED'::text CHECK (status = ANY (ARRAY['CREATED'::text, 'PENDING'::text, 'SUCCESS'::text, 'FAILED'::text, 'CANCELLED'::text, 'EXPIRED'::text])),
  return_url text,
  metadata jsonb,
  expires_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  payer_customer_id text,
  CONSTRAINT payment_orders_pkey PRIMARY KEY (payment_order_id),
  CONSTRAINT payment_orders_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(booking_id),
  CONSTRAINT payment_orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(customer_id),
  CONSTRAINT payment_orders_payer_customer_id_fkey FOREIGN KEY (payer_customer_id) REFERENCES public.customers(customer_id)
);
CREATE TABLE public.pg_refunds (
  pg_refund_id text NOT NULL DEFAULT (gen_random_uuid())::text,
  payment_order_id text NOT NULL,
  pg_transaction_id text NOT NULL,
  booking_payment_id text,
  provider text NOT NULL,
  provider_refund_id text,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  currency text NOT NULL DEFAULT 'INR'::text,
  reason text NOT NULL,
  status text NOT NULL DEFAULT 'INITIATED'::text CHECK (status = ANY (ARRAY['INITIATED'::text, 'PENDING'::text, 'SUCCESS'::text, 'FAILED'::text])),
  initiated_by text,
  raw_response jsonb,
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pg_refunds_pkey PRIMARY KEY (pg_refund_id),
  CONSTRAINT pg_refunds_payment_order_id_fkey FOREIGN KEY (payment_order_id) REFERENCES public.payment_orders(payment_order_id),
  CONSTRAINT pg_refunds_pg_transaction_id_fkey FOREIGN KEY (pg_transaction_id) REFERENCES public.pg_transactions(pg_transaction_id),
  CONSTRAINT pg_refunds_booking_payment_id_fkey FOREIGN KEY (booking_payment_id) REFERENCES public.booking_payments(payment_id),
  CONSTRAINT pg_refunds_initiated_by_fkey FOREIGN KEY (initiated_by) REFERENCES public.team_members(member_id)
);
CREATE TABLE public.pg_transactions (
  pg_transaction_id text NOT NULL DEFAULT (gen_random_uuid())::text,
  payment_order_id text NOT NULL,
  provider text NOT NULL,
  provider_transaction_id text,
  provider_order_id text,
  status text NOT NULL CHECK (status = ANY (ARRAY['PENDING'::text, 'SUCCESS'::text, 'FAILED'::text, 'CANCELLED'::text])),
  amount numeric NOT NULL,
  currency text NOT NULL DEFAULT 'INR'::text,
  payment_method text,
  payment_instrument text,
  error_code text,
  error_message text,
  webhook_event_type text,
  idempotency_key text NOT NULL UNIQUE,
  raw_response jsonb,
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pg_transactions_pkey PRIMARY KEY (pg_transaction_id),
  CONSTRAINT pg_transactions_payment_order_id_fkey FOREIGN KEY (payment_order_id) REFERENCES public.payment_orders(payment_order_id)
);
CREATE TABLE public.raw_moments (
  moment_id text NOT NULL,
  location text,
  image_url text NOT NULL,
  caption text,
  tags ARRAY DEFAULT '{}'::text[],
  is_featured boolean DEFAULT false,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  image_path text,
  CONSTRAINT raw_moments_pkey PRIMARY KEY (moment_id)
);
CREATE TABLE public.reviews (
  review_id text NOT NULL,
  trip_id text,
  customer_id text,
  reviewer_name text NOT NULL,
  reviewer_location text,
  reviewer_image_url text,
  trip_location text,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  review_text text NOT NULL,
  is_approved boolean NOT NULL DEFAULT false,
  is_featured boolean NOT NULL DEFAULT false,
  show_on_homepage boolean NOT NULL DEFAULT false,
  display_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT reviews_pkey PRIMARY KEY (review_id),
  CONSTRAINT reviews_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(trip_id),
  CONSTRAINT reviews_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(customer_id)
);
CREATE TABLE public.service_fulfillments (
  service_fulfillment_id text NOT NULL,
  booking_service_id text NOT NULL,
  vendor_booking_id text,
  fulfillment_status text NOT NULL DEFAULT 'pending'::text CHECK (fulfillment_status = ANY (ARRAY['pending'::text, 'submitted'::text, 'confirmed'::text, 'issued'::text, 'fulfilled'::text, 'cancelled'::text, 'failed'::text])),
  external_reference text,
  details_json jsonb,
  starts_at timestamp with time zone,
  ends_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT service_fulfillments_pkey PRIMARY KEY (service_fulfillment_id),
  CONSTRAINT service_fulfillments_booking_service_id_fkey FOREIGN KEY (booking_service_id) REFERENCES public.booking_services(booking_service_id),
  CONSTRAINT service_fulfillments_vendor_booking_id_fkey FOREIGN KEY (vendor_booking_id) REFERENCES public.vendor_bookings(vendor_booking_id)
);
CREATE TABLE public.signature_journeys (
  signature_journey_id text NOT NULL,
  journey_name text NOT NULL,
  destination_id text NOT NULL,
  duration_nights integer NOT NULL,
  duration_days integer NOT NULL,
  mrp_price numeric NOT NULL,
  description text,
  highlights text,
  is_listed boolean NOT NULL DEFAULT false,
  status text NOT NULL DEFAULT 'Active'::text CHECK (status = ANY (ARRAY['Active'::text, 'Inactive'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT signature_journeys_pkey PRIMARY KEY (signature_journey_id),
  CONSTRAINT signature_journeys_destination_id_fkey FOREIGN KEY (destination_id) REFERENCES public.destinations(destination_id)
);
CREATE TABLE public.site_gallery (
  gallery_id text NOT NULL,
  image_url text NOT NULL,
  thumbnail_url text,
  alt_text text,
  caption text,
  category text NOT NULL CHECK (category = ANY (ARRAY['cover'::text, 'hero'::text, 'itinerary'::text, 'accommodation'::text, 'activity'::text, 'gallery'::text])),
  trip_id text,
  location text,
  photographer text,
  is_featured boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  display_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  image_path text,
  CONSTRAINT site_gallery_pkey PRIMARY KEY (gallery_id),
  CONSTRAINT site_gallery_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(trip_id)
);
CREATE TABLE public.site_settings (
  id text NOT NULL DEFAULT 'main'::text,
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT site_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tasks (
  task_id text NOT NULL,
  title text NOT NULL,
  description text,
  entity_type text CHECK (entity_type IS NULL OR (entity_type = ANY (ARRAY['lead'::text, 'lead_trip'::text, 'customized_trip_request'::text, 'trip'::text, 'booking'::text, 'customer'::text, 'vendor'::text, 'invoice'::text]))),
  entity_id text,
  priority text NOT NULL DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text])),
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'in_progress'::text, 'done'::text, 'cancelled'::text, 'blocked'::text])),
  assignee_id text,
  created_by text NOT NULL,
  due_at timestamp with time zone,
  completed_at timestamp with time zone,
  completed_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tasks_pkey PRIMARY KEY (task_id),
  CONSTRAINT tasks_assignee_id_fkey FOREIGN KEY (assignee_id) REFERENCES public.team_members(member_id),
  CONSTRAINT tasks_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.team_members(member_id),
  CONSTRAINT tasks_completed_by_fkey FOREIGN KEY (completed_by) REFERENCES public.team_members(member_id)
);
CREATE TABLE public.team_members (
  member_id text NOT NULL,
  full_name text NOT NULL,
  email text UNIQUE,
  phone text,
  role text NOT NULL CHECK (role = ANY (ARRAY['Admin'::text, 'Sales'::text, 'Operations'::text, 'Finance'::text, 'Marketing'::text, 'Founder'::text, 'Captain'::text, 'Other'::text])),
  is_active boolean NOT NULL DEFAULT true,
  user_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  bio text,
  photo_url text,
  instagram text,
  display_order integer DEFAULT 0,
  CONSTRAINT team_members_pkey PRIMARY KEY (member_id)
);
CREATE TABLE public.traveller_types (
  slug text NOT NULL,
  name text NOT NULL,
  tagline text,
  description text,
  icon_key text,
  palette text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT traveller_types_pkey PRIMARY KEY (slug)
);
CREATE TABLE public.trip_captains_guides (
  trip_captain_id text NOT NULL,
  full_name text NOT NULL,
  phone text,
  phone_country_code text,
  phone_normalized text,
  email text,
  country text,
  city text,
  specialization text,
  languages_spoken ARRAY,
  experience integer,
  region_leading_in ARRAY,
  captain_type text CHECK (captain_type = ANY (ARRAY['trip_leader'::text, 'local_guide'::text])),
  rating numeric,
  is_active boolean NOT NULL DEFAULT true,
  trips_led_count integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  employee_id text,
  CONSTRAINT trip_captains_guides_pkey PRIMARY KEY (trip_captain_id)
);
CREATE TABLE public.trip_checklist_items (
  checklist_item_id text NOT NULL,
  trip_checklist_id text NOT NULL,
  template_item_id text,
  item_order integer NOT NULL DEFAULT 0,
  category text,
  title text NOT NULL,
  description text,
  assignee_id text,
  due_date date,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'done'::text, 'skipped'::text, 'blocked'::text])),
  completed_at timestamp with time zone,
  completed_by text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  stage text CHECK (stage = ANY (ARRAY['Pre-Trip'::text, 'Group Trip Prep'::text, 'WhatsApp Group'::text, 'On-Trip'::text, 'Post-Trip'::text])),
  CONSTRAINT trip_checklist_items_pkey PRIMARY KEY (checklist_item_id),
  CONSTRAINT trip_checklist_items_trip_checklist_id_fkey FOREIGN KEY (trip_checklist_id) REFERENCES public.trip_checklists(trip_checklist_id),
  CONSTRAINT trip_checklist_items_template_item_id_fkey FOREIGN KEY (template_item_id) REFERENCES public.checklist_template_items(template_item_id),
  CONSTRAINT trip_checklist_items_assignee_id_fkey FOREIGN KEY (assignee_id) REFERENCES public.team_members(member_id),
  CONSTRAINT trip_checklist_items_completed_by_fkey FOREIGN KEY (completed_by) REFERENCES public.team_members(member_id)
);
CREATE TABLE public.trip_checklists (
  trip_checklist_id text NOT NULL,
  trip_id text NOT NULL UNIQUE,
  template_id text,
  created_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT trip_checklists_pkey PRIMARY KEY (trip_checklist_id),
  CONSTRAINT trip_checklists_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(trip_id),
  CONSTRAINT trip_checklists_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.checklist_templates(template_id),
  CONSTRAINT trip_checklists_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.team_members(member_id)
);
CREATE TABLE public.trip_content (
  content_id text NOT NULL,
  trip_id text NOT NULL,
  content_type text NOT NULL CHECK (content_type = ANY (ARRAY['overview'::text, 'description'::text, 'tagline'::text, 'highlight'::text])),
  content_text text NOT NULL,
  content_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT trip_content_pkey PRIMARY KEY (content_id),
  CONSTRAINT trip_content_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(trip_id)
);
CREATE TABLE public.trip_costings (
  costing_id text NOT NULL,
  trip_id text,
  request_id text,
  costing_for text NOT NULL CHECK (costing_for = ANY (ARRAY['group_trip'::text, 'customized_trip'::text])),
  costing_type text NOT NULL CHECK (costing_type = ANY (ARRAY['domestic'::text, 'international'::text])),
  version integer NOT NULL DEFAULT 1,
  num_pax integer,
  scenarios jsonb NOT NULL DEFAULT '[]'::jsonb,
  pricing_summary jsonb,
  selected_scenario text,
  final_price_per_person numeric,
  markup_pct numeric,
  vendor_ref_link text,
  approval_status text NOT NULL DEFAULT 'not_required'::text CHECK (approval_status = ANY (ARRAY['not_required'::text, 'pending'::text, 'approved'::text, 'rejected'::text])),
  approved_by text,
  approved_at timestamp with time zone,
  approval_notes text,
  notes text,
  created_by text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  client_name text,
  ct_lead_id text,
  CONSTRAINT trip_costings_pkey PRIMARY KEY (costing_id),
  CONSTRAINT trip_costings_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.customized_trip_requests(request_id),
  CONSTRAINT trip_costings_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.team_members(member_id),
  CONSTRAINT trip_costings_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(trip_id),
  CONSTRAINT trip_costings_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.team_members(member_id)
);
CREATE TABLE public.trip_faqs (
  faq_id text NOT NULL,
  trip_id text NOT NULL,
  question text NOT NULL,
  answer text NOT NULL,
  category text,
  display_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT trip_faqs_pkey PRIMARY KEY (faq_id),
  CONSTRAINT trip_faqs_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(trip_id)
);
CREATE TABLE public.trip_gallery (
  gallery_id text NOT NULL,
  trip_id text NOT NULL,
  image_url text NOT NULL,
  thumbnail_url text,
  alt_text text,
  caption text,
  category text NOT NULL CHECK (category = ANY (ARRAY['cover'::text, 'hero'::text, 'itinerary'::text, 'accommodation'::text, 'activity'::text, 'gallery'::text])),
  is_cover boolean NOT NULL DEFAULT false,
  photographer text,
  display_order integer NOT NULL DEFAULT 0,
  is_featured boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  image_path text,
  CONSTRAINT trip_gallery_pkey PRIMARY KEY (gallery_id),
  CONSTRAINT trip_gallery_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(trip_id)
);
CREATE TABLE public.trip_inclusions (
  inclusion_id text NOT NULL,
  trip_id text NOT NULL,
  inclusion_type text NOT NULL CHECK (inclusion_type = ANY (ARRAY['inclusion'::text, 'exclusion'::text])),
  icon text,
  name text NOT NULL,
  note text,
  display_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT trip_inclusions_pkey PRIMARY KEY (inclusion_id),
  CONSTRAINT trip_inclusions_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(trip_id)
);
CREATE TABLE public.trip_itinerary (
  itinerary_id text NOT NULL,
  trip_id text NOT NULL,
  day_number integer NOT NULL,
  title text NOT NULL,
  subtitle text,
  description text,
  tags text,
  display_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT trip_itinerary_pkey PRIMARY KEY (itinerary_id),
  CONSTRAINT trip_itinerary_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(trip_id)
);
CREATE TABLE public.trips (
  trip_id text NOT NULL,
  slug text UNIQUE,
  trip_type text CHECK (trip_type IS NULL OR (trip_type = ANY (ARRAY['Community'::text, 'Beyond Ordinary'::text, 'Signature Journey'::text, 'Customized Trips Only'::text]))),
  destination_id text,
  trip_name text,
  duration_nights integer,
  duration_days integer,
  start_date date,
  end_date date,
  mrp_price numeric,
  selling_price numeric,
  discount_pct numeric,
  quoted_price numeric,
  advance_pct numeric DEFAULT 50,
  total_slots integer,
  booked_slots integer DEFAULT 0,
  number_of_pax integer,
  request_id text,
  batch_number text,
  is_listed boolean DEFAULT false,
  status text DEFAULT 'Draft'::text CHECK (status = ANY (ARRAY['Draft'::text, 'Upcoming'::text, 'Ongoing'::text, 'Completed'::text, 'Cancelled'::text])),
  dossier_url text,
  dossier_published_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  cancellation_policy_id text,
  source_draft_id text,
  legacy_trip_id text,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  trip_sub_type text,
  trip_category text,
  tagline text,
  tags ARRAY,
  departure_city text,
  departure_airport text,
  price_per text CHECK (price_per = ANY (ARRAY['per_person'::text, 'per_couple'::text, 'per_group'::text])),
  show_on_homepage boolean DEFAULT false,
  trip_captain_id text,
  booking_kind text NOT NULL DEFAULT 'trip'::text,
  currency_code text DEFAULT 'INR'::text,
  group_slug text,
  discount_amount numeric,
  last_autosaved_at timestamp with time zone,
  autosave_owner uuid,
  CONSTRAINT trips_pkey PRIMARY KEY (trip_id),
  CONSTRAINT trips_cancellation_policy_id_fkey FOREIGN KEY (cancellation_policy_id) REFERENCES public.cancellation_policies(policy_id),
  CONSTRAINT trips_trip_captain_id_fkey FOREIGN KEY (trip_captain_id) REFERENCES public.trip_captains_guides(trip_captain_id),
  CONSTRAINT trips_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.customized_trip_requests(request_id),
  CONSTRAINT trips_source_draft_id_fkey FOREIGN KEY (source_draft_id) REFERENCES public.itinerary_drafts(draft_id),
  CONSTRAINT trips_destination_id_fkey FOREIGN KEY (destination_id) REFERENCES public.destinations(destination_id)
);
CREATE TABLE public.user_moodboard_picks (
  id bigint NOT NULL DEFAULT nextval('customer_moodboard_picks_id_seq'::regclass),
  user_id text NOT NULL,
  pick_key text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_moodboard_picks_pkey PRIMARY KEY (id),
  CONSTRAINT fk_user_moodboard_picks_user_id FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.user_profiles (
  user_id text NOT NULL,
  about jsonb NOT NULL DEFAULT '{}'::jsonb,
  travel_style jsonb NOT NULL DEFAULT '{}'::jsonb,
  traveller_type text,
  traveller_type_revealed_at timestamp with time zone,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_profiles_pkey PRIMARY KEY (user_id),
  CONSTRAINT customer_profiles_traveller_type_fkey FOREIGN KEY (traveller_type) REFERENCES public.traveller_types(slug),
  CONSTRAINT fk_user_profiles_user_id FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.user_sessions (
  session_id text NOT NULL,
  user_id text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  last_used_at timestamp with time zone NOT NULL DEFAULT now(),
  ip text,
  user_agent text,
  revoked_at timestamp with time zone,
  CONSTRAINT user_sessions_pkey PRIMARY KEY (session_id),
  CONSTRAINT fk_user_sessions_user_id FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.user_wishlist (
  user_id text NOT NULL,
  trip_id text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_wishlist_pkey PRIMARY KEY (user_id, trip_id),
  CONSTRAINT customer_wishlist_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(trip_id),
  CONSTRAINT fk_user_wishlist_user_id FOREIGN KEY (user_id) REFERENCES public.users(user_id)
);
CREATE TABLE public.users (
  user_id text NOT NULL,
  customer_id text,
  phone text,
  phone_country_code text,
  phone_normalized text,
  full_name text,
  email text,
  avatar_url text,
  bio text,
  home_city text,
  signup_intent text CHECK (signup_intent = ANY (ARRAY['join'::text, 'booking'::text, 'callback'::text])),
  account_status text NOT NULL DEFAULT 'active'::text CHECK (account_status = ANY (ARRAY['active'::text, 'inactive'::text, 'blocked'::text])),
  last_login_at timestamp with time zone,
  onboarding_completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  lead_id text,
  CONSTRAINT users_pkey PRIMARY KEY (user_id),
  CONSTRAINT users_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(lead_id),
  CONSTRAINT users_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(customer_id)
);
CREATE TABLE public.vendor_bookings (
  vendor_booking_id text NOT NULL,
  trip_id text,
  vendor_id text NOT NULL,
  service_type text NOT NULL,
  description text,
  service_date_from date,
  service_date_to date,
  quantity integer NOT NULL DEFAULT 1,
  unit_cost numeric NOT NULL,
  total_cost numeric NOT NULL,
  currency_code text NOT NULL DEFAULT 'INR'::text,
  booking_reference text,
  voucher_url text,
  payment_status text NOT NULL DEFAULT 'Unpaid'::text CHECK (payment_status = ANY (ARRAY['Unpaid'::text, 'Advance Paid'::text, 'Paid'::text, 'Refunded'::text])),
  amount_paid numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'Requested'::text CHECK (status = ANY (ARRAY['Requested'::text, 'Confirmed'::text, 'Cancelled'::text, 'Completed'::text, 'No Show'::text])),
  notes text,
  created_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  booking_id text,
  booking_service_id text,
  CONSTRAINT vendor_bookings_pkey PRIMARY KEY (vendor_booking_id),
  CONSTRAINT vendor_bookings_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(vendor_id),
  CONSTRAINT vendor_bookings_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(trip_id),
  CONSTRAINT vendor_bookings_currency_code_fkey FOREIGN KEY (currency_code) REFERENCES public.currencies(currency_code),
  CONSTRAINT vendor_bookings_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.team_members(member_id),
  CONSTRAINT vendor_bookings_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(booking_id),
  CONSTRAINT vendor_bookings_booking_service_id_fkey FOREIGN KEY (booking_service_id) REFERENCES public.booking_services(booking_service_id)
);
CREATE TABLE public.vendor_invoices (
  vendor_invoice_id text NOT NULL,
  vendor_id text NOT NULL,
  vendor_booking_id text,
  trip_id text,
  vendor_invoice_number text,
  invoice_date date NOT NULL,
  due_date date,
  subtotal numeric NOT NULL,
  tax_amount numeric NOT NULL DEFAULT 0,
  total_amount numeric NOT NULL,
  currency_code text NOT NULL DEFAULT 'INR'::text,
  status text NOT NULL DEFAULT 'Received'::text CHECK (status = ANY (ARRAY['Received'::text, 'Approved'::text, 'Paid'::text, 'Disputed'::text, 'Cancelled'::text])),
  amount_paid numeric NOT NULL DEFAULT 0,
  paid_at date,
  file_url text,
  notes text,
  created_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT vendor_invoices_pkey PRIMARY KEY (vendor_invoice_id),
  CONSTRAINT vendor_invoices_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(vendor_id),
  CONSTRAINT vendor_invoices_vendor_booking_id_fkey FOREIGN KEY (vendor_booking_id) REFERENCES public.vendor_bookings(vendor_booking_id),
  CONSTRAINT vendor_invoices_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(trip_id),
  CONSTRAINT vendor_invoices_currency_code_fkey FOREIGN KEY (currency_code) REFERENCES public.currencies(currency_code),
  CONSTRAINT vendor_invoices_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.team_members(member_id)
);
CREATE TABLE public.vendor_payments (
  vendor_payment_id text NOT NULL,
  vendor_booking_id text NOT NULL,
  installment_type text NOT NULL CHECK (installment_type = ANY (ARRAY['advance'::text, 'balance'::text, 'full'::text, 'adjustment'::text])),
  amount numeric NOT NULL,
  currency_code text DEFAULT 'INR'::text,
  due_date date,
  paid_date date,
  payment_mode text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'paid'::text, 'partial'::text, 'failed'::text, 'cancelled'::text])),
  reference_no text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT vendor_payments_pkey PRIMARY KEY (vendor_payment_id),
  CONSTRAINT vendor_payments_vendor_booking_id_fkey FOREIGN KEY (vendor_booking_id) REFERENCES public.vendor_bookings(vendor_booking_id)
);
CREATE TABLE public.vendor_rate_cards (
  rate_card_id text NOT NULL,
  vendor_id text NOT NULL,
  package_name text NOT NULL,
  destination text,
  duration_days integer,
  duration_nights integer,
  pax_slab text,
  base_price numeric,
  currency_code text DEFAULT 'INR'::text,
  season text,
  valid_from date,
  valid_to date,
  raw_pricing jsonb,
  source_file text,
  source_sheet text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  destination_id text,
  rate_type text CHECK (rate_type = ANY (ARRAY['per_person'::text, 'per_room_per_night'::text, 'per_vehicle_per_day'::text, 'flat'::text, 'per_unit'::text])),
  pax_min integer,
  pax_max integer,
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT vendor_rate_cards_pkey PRIMARY KEY (rate_card_id),
  CONSTRAINT vendor_rate_cards_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(vendor_id),
  CONSTRAINT vendor_rate_cards_destination_id_fkey FOREIGN KEY (destination_id) REFERENCES public.destinations(destination_id)
);
CREATE TABLE public.vendors (
  vendor_id text NOT NULL,
  vendor_name text NOT NULL,
  category text NOT NULL CHECK (category IS NULL OR (category = ANY (ARRAY['hotel'::text, 'transport'::text, 'dmc'::text, 'hotel_chain'::text, 'visa_service'::text, 'activity'::text, 'other'::text]))),
  destination_id text,
  city text,
  contact_name text,
  contact_phone text,
  contact_email text,
  gstin text,
  pan text,
  address text,
  rating numeric CHECK (rating IS NULL OR rating >= 0::numeric AND rating <= 5::numeric),
  is_preferred boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  payment_terms text,
  notes text,
  created_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  country_scope text CHECK (country_scope IS NULL OR (country_scope = ANY (ARRAY['domestic'::text, 'international'::text]))),
  point_of_contact text,
  poc_phone text,
  poc_email text,
  platform text,
  state text,
  country text,
  region text,
  CONSTRAINT vendors_pkey PRIMARY KEY (vendor_id),
  CONSTRAINT vendors_destination_id_fkey FOREIGN KEY (destination_id) REFERENCES public.destinations(destination_id),
  CONSTRAINT vendors_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.team_members(member_id)
);